version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql/mysql-server:8.0.32
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    networks:
      - app_network

  backend:
    container_name: backend
    restart: on-failure
    build:
      context: ./Backend/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - mysql
    networks:
      - app_network

  nextjs:
    container_name: nextjs
    build:
      context: ./Frontend/
      dockerfile: Dockerfile
    ports:
      - "${NEXTJS_PORT}:3000"
    restart: unless-stopped
    networks:
      - app_network

  nginx:
    container_name: nginx
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/sirokuma/certificates/fullchain.pem:/etc/letsencrypt/live/sirokuma-server.site/fullchain.pem
      - /home/sirokuma/certificates/privkey.pem:/etc/letsencrypt/live/sirokuma-server.site/privkey.pem
      - /home/sirokuma/certificates:/etc/letsencrypt
      - ./nginx/html:/var/www/html
    depends_on:
      - backend
      - nextjs
    networks:
      - app_network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /home/sirokuma/certificates:/etc/letsencrypt
      - ./nginx/html:/var/www/html
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/html; sleep 12h; done'"
    networks:
      - app_network

networks:
  app_network:

volumes:
  mysql_data:

